language: r
dist: xenial
cache: packages

r_packages:
  - devtools
  - ggplot2
  - hunspell
  - nLTT
  - xml2
  - xtable

r_github_packages:
  - Giappo/mbd
  - jimhester/covr
  - jimhester/lintr
  - ropensci/beastier
  - ropensci/mauricer
  - ropensci/babette
  - richelbilderbeek/mcbette
  - richelbilderbeek/ribir
  - richelbilderbeek/becosys
  - richelbilderbeek/pirouette@richel
  - MangoTheCat/goodpractice
  - KlausVigo/phangorn
  - ropensci/spelling

bioc_packages:
  - ggtree

before_install:
  - echo $TRAVIS_R_VERSION_STRING
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
  # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi

before_script:
  - Rscript -e "beastier::install_beast2()"
  - Rscript -e "mauricer::install_beast2_pkg(\"NS\")"

script:
  - travis_wait 60 Rscript example_9.R

after_success:
  - cd ~/GitHubs/pirouette_article; find .
