language: r
cache: packages

r_github_packages:
  - richelbilderbeek/tiebeaur
  - thijsjanzen/nodeSub
  - richelbilderbeek/pirouette

before_install:
  # Fix rJava error, from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
  - sudo $(which R) CMD javareconf
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
  # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi

before_script:
  - Rscript -e "beastier::install_beast2()"
  - Rscript -e "mauricer::install_beast2_pkg(\"NS\")"

script:
  - echo "Nothing for now"
  #- travis_wait 60 ./scripts/rerun.sh

after_success:
  - Rscript -e "mcbette::mcbette_report()"
  - find .
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

after_failure:
  - Rscript -e "mcbette::mcbette_report()"
  - find .
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

